export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';
export const SEARCH_SINGLE_USER_SUCCESS = 'SEARCH_SINGLE_USER_SUCCESS';
export const SEARCH_SINGLE_USER_FAIL = 'SEARCH_SINGLE_USER_FAIL';
export const RESET_LOADING = 'RESET_LOADING';
