export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';
export const SEARCH_SINGLE_USER_SUCCESS = 'SEARCH_SINGLE_USER_SUCCESS';
export const SEARCH_SINGLE_USER_FAIL = 'SEARCH_SINGLE_USER_FAIL';
export const RESET_LOADING_USER_LOADING = 'RESET_LOADING_USER_LOADING';
export const RESET_LOADING_USERS_LOADING = 'RESET_LOADING_USERS_LOADING';
export const TOGGLE_FOLLOW = 'TOGGLE_FOLLOW';
