export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GET_FOLLOWING = 'GET_FOLLOWING';
export const FOLLOWERS_ERROR = 'FOLLOWERS_ERROR';
export const FOLLOWING_ERROR = 'FOLLOWING_ERROR';
export const RESET_FOLLOWERS_LOADING = 'RESET_FOLLOWERS_LOADING';
export const RESET_FOLLOWING_LOADING = 'RESET_FOLLOWING_LOADING';
