export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const SET_FOLLOWING = 'SET_FOLLOWING';
export const FOLLOWERS_ERROR = 'FOLLOWERS_ERROR';
export const FOLLOWING_ERROR = 'FOLLOWING_ERROR';
export const RESET_FOLLOWERS_LOADING = 'RESET_FOLLOWERS_LOADING';
export const RESET_FOLLOWING_LOADING = 'RESET_FOLLOWING_LOADING';
