export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_LOADED_ERROR = 'POSTS_LOADED_ERROR';
export const POSTS_OF_USER_LOADED = 'POSTS_OF_USER_LOADED';
export const POSTS_OF_USER_LOADED_ERROR = 'POSTS_OF_USER_LOADED_ERROR';
