export const SET_PROFILE = 'SET_PROFILE';
export const SET_EMPTY_PROFILE = 'SET_EMPTY_PROFILE';
export const RESET_PROFILE_LOADING = 'RESET_PROFILE_LOADING';
export const TOGGLE_PROFILE_FOLLOW = 'TOGGLE_PROFILE_FOLLOW';
export const RESET_PROFILE = 'RESET_PROFILE';
export const SET_PROFILE_FOLLOWING_COUNT = 'SET_PROFILE_FOLLOWING_COUNT';
