export const SET_ACTIVITIES_FEED = 'SET_ACTIVITIES_FEED';
export const SET_ACTIVITIES_FEED_FOLLOWS = 'SET_ACTIVITIES_FEED_FOLLOWS';
export const TOGGLE_ACTIVITIES_FEED_FOLLOWS = 'TOGGLE_ACTIVITIES_FEED_FOLLOWS';
