export const SET_POST = 'SET_POST';
export const RESET_POST = 'RESET_POST';
export const TOGGLE_POST_OWNER_FOLLOW = 'TOGGLE_POST_OWNER_FOLLOW';
export const TOGGLE_POST_COMMENT_LIKE = 'TOGGLE_POST_COMMENT_LIKE';
