export const SET_POST = 'SET_POST';
export const RESET_POST = 'RESET_POST';
export const TOGGLE_POST_OWNER_FOLLOW = 'TOGGLE_POST_OWNER_FOLLOW';
export const TOGGLE_POST_COMMENT_LIKE = 'TOGGLE_POST_COMMENT_LIKE';
export const TOGGLE_POST_LIKE = 'TOGGLE_POST_LIKE';
export const ADD_COMMENT_TO_POST = 'ADD_COMMENT_TO_POST';
export const TOGGLE_POST_LIKE_FAILED = 'TOGGLE_POST_LIKE_FAILED';
export const TOGGLE_POST_LIKE_REQUESTED = 'TOGGLE_POST_LIKE_REQUESTED';

