export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';
export const RESET_USERS_LOADING = 'RESET_USERS_LOADING';
export const RESET_USERS = 'RESET_USERS_LOADING';
